#!/bin/bash

# Install necessary packages
sudo apt update -y
sudo apt install apache2 wget cron unzip nfs-common -y
sudo bash -c "cd /var/www/html && mv index.html index.html.old"
sudo a2enmod rewrite

# Install PHP 8.3 and related packages
sudo apt install php8.3-fpm php8.3-mysql php8.3-common php8.3-cli php8.3-curl php8.3-gd php8.3-xml php8.3-mbstring php8.3-zip php8.3-intl -y
sudo a2enmod proxy_fcgi setenvif
sudo a2enconf php8.3-fpm
sudo systemctl restart apache2


# Install phpMyAdmin (optional, you can skip if unnecessary)
sudo a2enconf phpmyadmin
sudo systemctl restart apache2

# Mount EFS
sudo bash -c "mount -t fs-05dfa2f808d330269.efs.us-west-2.amazonaws.com:/ /var/www/html && sudo mount -a "

# Ensure EFS is mounted
line_to_add="fs-05dfa2f808d330269.efs.us-west-2.amazonaws.com:/ /var/www/html nfs4 defaults 0 0"
file_path="/etc/fstab"

grep -qxF "$line_to_add" "$file_path" || echo "$line_to_add" >> "$file_path"

# Mount EFS
sudo mount -a


# Set proper permissions for WordPress files (ensuring www-data has access)
sudo chmod -R 755 /var/www/html
sudo chown -R www-data:www-data /var/www/html


# Only install WordPress if it's not already present
if [ ! -f /var/www/html/wp-config.php ]; then
  echo "Installing WordPress..."
  sudo bash -c "cd /var/www/html && wget https://wordpress.org/latest.zip"
  sudo unzip /var/www/html/latest.zip -d /var/www/html/
  sudo mv /var/www/html/wordpress/* /var/www/html/
  sudo bash -c "cd /var/www/html && rm -rf wordpress latest.zip"
fi

# Ensure wp-config.php exists (if not, create an empty one)
sudo touch /var/www/html/wp-config.php
sudo chown -R www-data:www-data /var/www/html/wp-config.php

# Enable Apache site configuration
sudo bash -c "cd /etc/apache2/sites-available && a2ensite 000-default.conf"
sudo systemctl restart apache2


echo "WordPress installation completed."


