#!/bin/bash

# Install necessary packages
sudo apt update -y
sudo apt install apache2 wget cron unzip nfs-common -y
sudo bash -c "cd /var/www/html && mv index.html index.html.old"
sudo a2enmod rewrite

# Install PHP 8.3 and related packages
sudo apt install php8.3-fpm php8.3-mysql php8.3-common php8.3-cli php8.3-curl php8.3-gd php8.3-xml php8.3-mbstring php8.3-zip php8.3-intl -y
sudo a2enmod proxy_fcgi setenvif
sudo a2enconf php8.3-fpm
sudo systemctl restart apache2


# Install phpMyAdmin (optional, you can skip if unnecessary)
sudo a2enconf phpmyadmin
sudo systemctl restart apache2

# Mount EFS
echo "Mounting EFS to /var/www/html..."
sudo bash -c "mount -t fs-05dfa2f808d330269.efs.us-west-2.amazonaws.com:/ /var/www/html && sudo mount -a "

# Ensure EFS is mounted
echo "Ensuring EFS mount is persistent..."
line_to_add="fs-05dfa2f808d330269.efs.us-west-2.amazonaws.com:/ /var/www/html nfs4 defaults 0 0"
file_path="/etc/fstab"

grep -qxF "$line_to_add" "$file_path" || echo "$line_to_add" >> "$file_path"

# Mount EFS
echo "Mounting all filesystems defined in fstab..."
sudo mount -a

echo "EFS mounted successfully."









