#!/bin/bash
sudo systemctl restart codedeploy-agent.service
sudo systemctl start apache2
sudo systemctl start php8.3-fpm
sudo systemctl enable php8.3-fpm
sudo systemctl start cron
sudo systemctl enable cron
