#!/bin/bash

# Stop nginx service
# sudo systemctl stop nginx
# sudo systemctl disable nginx

# Check if Apache is running
isExistApp=$(pgrep apache2)
if [[ -n  $isExistApp ]]; then
    service apache2 stop        
fi

